/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7-dev */

#include "protocol/phy/phy.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(phy_SetASKModulationCmd, phy_SetASKModulationCmd, AUTO)


PB_BIND(phy_SetFSKModulationCmd, phy_SetFSKModulationCmd, AUTO)


PB_BIND(phy_SetGFSKModulationCmd, phy_SetGFSKModulationCmd, AUTO)


PB_BIND(phy_SetBPSKModulationCmd, phy_SetBPSKModulationCmd, AUTO)


PB_BIND(phy_SetQPSKModulationCmd, phy_SetQPSKModulationCmd, AUTO)


PB_BIND(phy_GetSupportedFrequenciesCmd, phy_GetSupportedFrequenciesCmd, AUTO)


PB_BIND(phy_SetFrequencyCmd, phy_SetFrequencyCmd, AUTO)


PB_BIND(phy_SetDataRateCmd, phy_SetDataRateCmd, AUTO)


PB_BIND(phy_SetEndiannessCmd, phy_SetEndiannessCmd, AUTO)


PB_BIND(phy_SetTXPowerCmd, phy_SetTXPowerCmd, AUTO)


PB_BIND(phy_SetPacketSizeCmd, phy_SetPacketSizeCmd, AUTO)


PB_BIND(phy_SetSyncWordCmd, phy_SetSyncWordCmd, AUTO)


PB_BIND(phy_SniffCmd, phy_SniffCmd, AUTO)


PB_BIND(phy_SendCmd, phy_SendCmd, 2)


PB_BIND(phy_SendRawCmd, phy_SendRawCmd, AUTO)


PB_BIND(phy_StartCmd, phy_StartCmd, AUTO)


PB_BIND(phy_StopCmd, phy_StopCmd, AUTO)


PB_BIND(phy_JamCmd, phy_JamCmd, AUTO)


PB_BIND(phy_MonitorCmd, phy_MonitorCmd, AUTO)


PB_BIND(phy_PacketReceived, phy_PacketReceived, 2)


PB_BIND(phy_RawPacketReceived, phy_RawPacketReceived, 2)


PB_BIND(phy_Jammed, phy_Jammed, AUTO)


PB_BIND(phy_MonitoringReport, phy_MonitoringReport, AUTO)


PB_BIND(phy_SupportedFrequencyRanges, phy_SupportedFrequencyRanges, AUTO)


PB_BIND(phy_SupportedFrequencyRanges_FrequencyRange, phy_SupportedFrequencyRanges_FrequencyRange, AUTO)


PB_BIND(phy_Message, phy_Message, 2)







