/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7-dev */

#include "protocol/ble/ble.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ble_SetBdAddressCmd, ble_SetBdAddressCmd, AUTO)


PB_BIND(ble_SniffAdvCmd, ble_SniffAdvCmd, AUTO)


PB_BIND(ble_JamAdvCmd, ble_JamAdvCmd, AUTO)


PB_BIND(ble_JamAdvOnChannelCmd, ble_JamAdvOnChannelCmd, AUTO)


PB_BIND(ble_SniffConnReqCmd, ble_SniffConnReqCmd, AUTO)


PB_BIND(ble_SniffAccessAddressCmd, ble_SniffAccessAddressCmd, AUTO)


PB_BIND(ble_SniffActiveConnCmd, ble_SniffActiveConnCmd, AUTO)


PB_BIND(ble_JamConnCmd, ble_JamConnCmd, AUTO)


PB_BIND(ble_ScanModeCmd, ble_ScanModeCmd, AUTO)


PB_BIND(ble_AdvModeCmd, ble_AdvModeCmd, AUTO)


PB_BIND(ble_SetAdvDataCmd, ble_SetAdvDataCmd, AUTO)


PB_BIND(ble_CentralModeCmd, ble_CentralModeCmd, AUTO)


PB_BIND(ble_ConnectToCmd, ble_ConnectToCmd, AUTO)


PB_BIND(ble_SendRawPDUCmd, ble_SendRawPDUCmd, 2)


PB_BIND(ble_SendPDUCmd, ble_SendPDUCmd, 2)


PB_BIND(ble_DisconnectCmd, ble_DisconnectCmd, AUTO)


PB_BIND(ble_PeripheralModeCmd, ble_PeripheralModeCmd, AUTO)


PB_BIND(ble_StartCmd, ble_StartCmd, AUTO)


PB_BIND(ble_StopCmd, ble_StopCmd, AUTO)


PB_BIND(ble_HijackMasterCmd, ble_HijackMasterCmd, AUTO)


PB_BIND(ble_HijackSlaveCmd, ble_HijackSlaveCmd, AUTO)


PB_BIND(ble_HijackBothCmd, ble_HijackBothCmd, AUTO)


PB_BIND(ble_SetEncryptionCmd, ble_SetEncryptionCmd, AUTO)


PB_BIND(ble_ReactiveJamCmd, ble_ReactiveJamCmd, AUTO)


PB_BIND(ble_PrepareSequenceCmd, ble_PrepareSequenceCmd, 4)


PB_BIND(ble_PrepareSequenceCmd_ReceptionTrigger, ble_PrepareSequenceCmd_ReceptionTrigger, 2)


PB_BIND(ble_PrepareSequenceCmd_ConnectionEventTrigger, ble_PrepareSequenceCmd_ConnectionEventTrigger, AUTO)


PB_BIND(ble_PrepareSequenceCmd_ManualTrigger, ble_PrepareSequenceCmd_ManualTrigger, AUTO)


PB_BIND(ble_PrepareSequenceCmd_Trigger, ble_PrepareSequenceCmd_Trigger, 2)


PB_BIND(ble_PrepareSequenceCmd_PendingPacket, ble_PrepareSequenceCmd_PendingPacket, 2)


PB_BIND(ble_TriggerSequenceCmd, ble_TriggerSequenceCmd, AUTO)


PB_BIND(ble_TriggerChange, ble_TriggerChange, AUTO)


PB_BIND(ble_AccessAddressDiscovered, ble_AccessAddressDiscovered, AUTO)


PB_BIND(ble_AdvPduReceived, ble_AdvPduReceived, AUTO)


PB_BIND(ble_Connected, ble_Connected, AUTO)


PB_BIND(ble_Disconnected, ble_Disconnected, AUTO)


PB_BIND(ble_Synchronized, ble_Synchronized, AUTO)


PB_BIND(ble_Desynchronized, ble_Desynchronized, AUTO)


PB_BIND(ble_Hijacked, ble_Hijacked, AUTO)


PB_BIND(ble_Injected, ble_Injected, AUTO)


PB_BIND(ble_RawPduReceived, ble_RawPduReceived, 2)


PB_BIND(ble_PduReceived, ble_PduReceived, 2)


PB_BIND(ble_Message, ble_Message, 4)








