/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7-dev */

#include "protocol/unifying/unifying.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(unifying_SetNodeAddressCmd, unifying_SetNodeAddressCmd, AUTO)


PB_BIND(unifying_SniffCmd, unifying_SniffCmd, AUTO)


PB_BIND(unifying_JamCmd, unifying_JamCmd, AUTO)


PB_BIND(unifying_SendCmd, unifying_SendCmd, 2)


PB_BIND(unifying_SendRawCmd, unifying_SendRawCmd, 2)


PB_BIND(unifying_LogitechDongleModeCmd, unifying_LogitechDongleModeCmd, AUTO)


PB_BIND(unifying_LogitechKeyboardModeCmd, unifying_LogitechKeyboardModeCmd, AUTO)


PB_BIND(unifying_LogitechMouseModeCmd, unifying_LogitechMouseModeCmd, AUTO)


PB_BIND(unifying_StartCmd, unifying_StartCmd, AUTO)


PB_BIND(unifying_StopCmd, unifying_StopCmd, AUTO)


PB_BIND(unifying_SniffPairingCmd, unifying_SniffPairingCmd, AUTO)


PB_BIND(unifying_Jammed, unifying_Jammed, AUTO)


PB_BIND(unifying_RawPduReceived, unifying_RawPduReceived, 2)


PB_BIND(unifying_PduReceived, unifying_PduReceived, 2)


PB_BIND(unifying_Message, unifying_Message, 2)




