/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7-dev */

#include "protocol/zigbee/zigbee.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(zigbee_SetNodeAddressCmd, zigbee_SetNodeAddressCmd, AUTO)


PB_BIND(zigbee_SniffCmd, zigbee_SniffCmd, AUTO)


PB_BIND(zigbee_JamCmd, zigbee_JamCmd, AUTO)


PB_BIND(zigbee_SendCmd, zigbee_SendCmd, 2)


PB_BIND(zigbee_EndDeviceCmd, zigbee_EndDeviceCmd, AUTO)


PB_BIND(zigbee_RouterCmd, zigbee_RouterCmd, AUTO)


PB_BIND(zigbee_CoordinatorCmd, zigbee_CoordinatorCmd, AUTO)


PB_BIND(zigbee_StartCmd, zigbee_StartCmd, AUTO)


PB_BIND(zigbee_StopCmd, zigbee_StopCmd, AUTO)


PB_BIND(zigbee_ManInTheMiddleCmd, zigbee_ManInTheMiddleCmd, AUTO)


PB_BIND(zigbee_Jammed, zigbee_Jammed, AUTO)


PB_BIND(zigbee_RawPduReceived, zigbee_RawPduReceived, 2)


PB_BIND(zigbee_PduReceived, zigbee_PduReceived, 2)


PB_BIND(zigbee_Message, zigbee_Message, 2)





