/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7-dev */

#ifndef PB_DISCOVERY_PROTOCOL_DEVICE_PB_H_INCLUDED
#define PB_DISCOVERY_PROTOCOL_DEVICE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Domains definition. */
typedef enum _discovery_Domain { 
    discovery_Domain__DomainNone = 0, 
    discovery_Domain_Generic = 16777216, 
    discovery_Domain_BtClassic = 33554432, 
    discovery_Domain_BtLE = 50331648, 
    discovery_Domain_Zigbee = 67108864, 
    discovery_Domain_SixLowPan = 83886080, 
    discovery_Domain_Esb = 100663296, 
    discovery_Domain_LogitechUnifying = 117440512, 
    discovery_Domain_Mosart = 134217728, 
    discovery_Domain_ANT = 150994944, 
    discovery_Domain_ANT_Plus = 167772160, 
    discovery_Domain_ANT_FS = 184549376 
} discovery_Domain;

/* *
 DeviceType specifies the supported devices. */
typedef enum _discovery_DeviceType { 
    discovery_DeviceType_Esp32BleFuzzer = 0, 
    discovery_DeviceType_Butterfly = 1, 
    discovery_DeviceType_BtleJack = 2, 
    discovery_DeviceType_VirtualDevice = 4 
} discovery_DeviceType;

typedef enum _discovery_Capability { 
    discovery_Capability__CapNone = 0, 
    discovery_Capability_Scan = 1, 
    discovery_Capability_Sniff = 2, 
    discovery_Capability_Inject = 4, 
    discovery_Capability_Jam = 8, 
    discovery_Capability_Hijack = 16, 
    discovery_Capability_Hook = 32, 
    discovery_Capability_MasterRole = 64, 
    discovery_Capability_SlaveRole = 128, 
    discovery_Capability_NoRawData = 256, 
    discovery_Capability_EndDeviceRole = 257, 
    discovery_Capability_CoordinatorRole = 258, 
    discovery_Capability_RouterRole = 260 
} discovery_Capability;

/* Struct definitions */
typedef struct _discovery_DeviceReadyResp { 
    char dummy_field;
} discovery_DeviceReadyResp;

typedef struct _discovery_DeviceResetQuery { 
    char dummy_field;
} discovery_DeviceResetQuery;

typedef struct _discovery_DeviceDomainInfoQuery { 
    uint32_t domain;
} discovery_DeviceDomainInfoQuery;

typedef struct _discovery_DeviceDomainInfoResp { 
    uint32_t domain;
    uint64_t supported_commands;
} discovery_DeviceDomainInfoResp;

typedef struct _discovery_DeviceInfoQuery { 
    uint32_t proto_ver;
} discovery_DeviceInfoQuery;

typedef PB_BYTES_ARRAY_T(64) discovery_DeviceInfoResp_fw_author_t;
typedef PB_BYTES_ARRAY_T(256) discovery_DeviceInfoResp_fw_url_t;
typedef struct _discovery_DeviceInfoResp { 
    /* Device type. */
    uint32_t type;
    /* Device ID */
    pb_byte_t devid[16];
    /* Supported minimal protocol version. */
    uint32_t proto_min_ver;
    /* Maximum supported speed (if useful). */
    uint32_t max_speed;
    /* Device firmware info. */
    discovery_DeviceInfoResp_fw_author_t fw_author;
    discovery_DeviceInfoResp_fw_url_t fw_url;
    uint32_t fw_version_major;
    uint32_t fw_version_minor;
    uint32_t fw_version_rev;
    pb_callback_t capabilities;
} discovery_DeviceInfoResp;

typedef struct _discovery_SetTransportSpeed { 
    uint32_t speed;
} discovery_SetTransportSpeed;

typedef struct _discovery_Message { 
    pb_size_t which_msg;
    union {
        discovery_DeviceResetQuery reset_query;
        discovery_DeviceReadyResp ready_resp;
        discovery_DeviceInfoQuery info_query;
        discovery_DeviceInfoResp info_resp;
        discovery_DeviceDomainInfoQuery domain_query;
        discovery_DeviceDomainInfoResp domain_resp;
        discovery_SetTransportSpeed set_speed;
    } msg;
} discovery_Message;


/* Helper constants for enums */
#define _discovery_Domain_MIN discovery_Domain__DomainNone
#define _discovery_Domain_MAX discovery_Domain_ANT_FS
#define _discovery_Domain_ARRAYSIZE ((discovery_Domain)(discovery_Domain_ANT_FS+1))

#define _discovery_DeviceType_MIN discovery_DeviceType_Esp32BleFuzzer
#define _discovery_DeviceType_MAX discovery_DeviceType_VirtualDevice
#define _discovery_DeviceType_ARRAYSIZE ((discovery_DeviceType)(discovery_DeviceType_VirtualDevice+1))

#define _discovery_Capability_MIN discovery_Capability__CapNone
#define _discovery_Capability_MAX discovery_Capability_RouterRole
#define _discovery_Capability_ARRAYSIZE ((discovery_Capability)(discovery_Capability_RouterRole+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define discovery_DeviceResetQuery_init_default  {0}
#define discovery_DeviceReadyResp_init_default   {0}
#define discovery_SetTransportSpeed_init_default {0}
#define discovery_DeviceInfoResp_init_default    {0, {0}, 0, 0, {0, {0}}, {0, {0}}, 0, 0, 0, {{NULL}, NULL}}
#define discovery_DeviceDomainInfoResp_init_default {0, 0}
#define discovery_DeviceInfoQuery_init_default   {0}
#define discovery_DeviceDomainInfoQuery_init_default {0}
#define discovery_Message_init_default           {0, {discovery_DeviceResetQuery_init_default}}
#define discovery_DeviceResetQuery_init_zero     {0}
#define discovery_DeviceReadyResp_init_zero      {0}
#define discovery_SetTransportSpeed_init_zero    {0}
#define discovery_DeviceInfoResp_init_zero       {0, {0}, 0, 0, {0, {0}}, {0, {0}}, 0, 0, 0, {{NULL}, NULL}}
#define discovery_DeviceDomainInfoResp_init_zero {0, 0}
#define discovery_DeviceInfoQuery_init_zero      {0}
#define discovery_DeviceDomainInfoQuery_init_zero {0}
#define discovery_Message_init_zero              {0, {discovery_DeviceResetQuery_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define discovery_DeviceDomainInfoQuery_domain_tag 1
#define discovery_DeviceDomainInfoResp_domain_tag 1
#define discovery_DeviceDomainInfoResp_supported_commands_tag 2
#define discovery_DeviceInfoQuery_proto_ver_tag  1
#define discovery_DeviceInfoResp_type_tag        1
#define discovery_DeviceInfoResp_devid_tag       2
#define discovery_DeviceInfoResp_proto_min_ver_tag 3
#define discovery_DeviceInfoResp_max_speed_tag   4
#define discovery_DeviceInfoResp_fw_author_tag   5
#define discovery_DeviceInfoResp_fw_url_tag      6
#define discovery_DeviceInfoResp_fw_version_major_tag 7
#define discovery_DeviceInfoResp_fw_version_minor_tag 8
#define discovery_DeviceInfoResp_fw_version_rev_tag 9
#define discovery_DeviceInfoResp_capabilities_tag 10
#define discovery_SetTransportSpeed_speed_tag    1
#define discovery_Message_reset_query_tag        1
#define discovery_Message_ready_resp_tag         2
#define discovery_Message_info_query_tag         3
#define discovery_Message_info_resp_tag          4
#define discovery_Message_domain_query_tag       5
#define discovery_Message_domain_resp_tag        6
#define discovery_Message_set_speed_tag          7

/* Struct field encoding specification for nanopb */
#define discovery_DeviceResetQuery_FIELDLIST(X, a) \

#define discovery_DeviceResetQuery_CALLBACK NULL
#define discovery_DeviceResetQuery_DEFAULT NULL

#define discovery_DeviceReadyResp_FIELDLIST(X, a) \

#define discovery_DeviceReadyResp_CALLBACK NULL
#define discovery_DeviceReadyResp_DEFAULT NULL

#define discovery_SetTransportSpeed_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   speed,             1)
#define discovery_SetTransportSpeed_CALLBACK NULL
#define discovery_SetTransportSpeed_DEFAULT NULL

#define discovery_DeviceInfoResp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   type,              1) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, devid,             2) \
X(a, STATIC,   SINGULAR, UINT32,   proto_min_ver,     3) \
X(a, STATIC,   SINGULAR, UINT32,   max_speed,         4) \
X(a, STATIC,   SINGULAR, BYTES,    fw_author,         5) \
X(a, STATIC,   SINGULAR, BYTES,    fw_url,            6) \
X(a, STATIC,   SINGULAR, UINT32,   fw_version_major,   7) \
X(a, STATIC,   SINGULAR, UINT32,   fw_version_minor,   8) \
X(a, STATIC,   SINGULAR, UINT32,   fw_version_rev,    9) \
X(a, CALLBACK, REPEATED, UINT32,   capabilities,     10)
#define discovery_DeviceInfoResp_CALLBACK pb_default_field_callback
#define discovery_DeviceInfoResp_DEFAULT NULL

#define discovery_DeviceDomainInfoResp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   domain,            1) \
X(a, STATIC,   SINGULAR, UINT64,   supported_commands,   2)
#define discovery_DeviceDomainInfoResp_CALLBACK NULL
#define discovery_DeviceDomainInfoResp_DEFAULT NULL

#define discovery_DeviceInfoQuery_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   proto_ver,         1)
#define discovery_DeviceInfoQuery_CALLBACK NULL
#define discovery_DeviceInfoQuery_DEFAULT NULL

#define discovery_DeviceDomainInfoQuery_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   domain,            1)
#define discovery_DeviceDomainInfoQuery_CALLBACK NULL
#define discovery_DeviceDomainInfoQuery_DEFAULT NULL

#define discovery_Message_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,reset_query,msg.reset_query),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,ready_resp,msg.ready_resp),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,info_query,msg.info_query),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,info_resp,msg.info_resp),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,domain_query,msg.domain_query),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,domain_resp,msg.domain_resp),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,set_speed,msg.set_speed),   7)
#define discovery_Message_CALLBACK NULL
#define discovery_Message_DEFAULT NULL
#define discovery_Message_msg_reset_query_MSGTYPE discovery_DeviceResetQuery
#define discovery_Message_msg_ready_resp_MSGTYPE discovery_DeviceReadyResp
#define discovery_Message_msg_info_query_MSGTYPE discovery_DeviceInfoQuery
#define discovery_Message_msg_info_resp_MSGTYPE discovery_DeviceInfoResp
#define discovery_Message_msg_domain_query_MSGTYPE discovery_DeviceDomainInfoQuery
#define discovery_Message_msg_domain_resp_MSGTYPE discovery_DeviceDomainInfoResp
#define discovery_Message_msg_set_speed_MSGTYPE discovery_SetTransportSpeed

extern const pb_msgdesc_t discovery_DeviceResetQuery_msg;
extern const pb_msgdesc_t discovery_DeviceReadyResp_msg;
extern const pb_msgdesc_t discovery_SetTransportSpeed_msg;
extern const pb_msgdesc_t discovery_DeviceInfoResp_msg;
extern const pb_msgdesc_t discovery_DeviceDomainInfoResp_msg;
extern const pb_msgdesc_t discovery_DeviceInfoQuery_msg;
extern const pb_msgdesc_t discovery_DeviceDomainInfoQuery_msg;
extern const pb_msgdesc_t discovery_Message_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define discovery_DeviceResetQuery_fields &discovery_DeviceResetQuery_msg
#define discovery_DeviceReadyResp_fields &discovery_DeviceReadyResp_msg
#define discovery_SetTransportSpeed_fields &discovery_SetTransportSpeed_msg
#define discovery_DeviceInfoResp_fields &discovery_DeviceInfoResp_msg
#define discovery_DeviceDomainInfoResp_fields &discovery_DeviceDomainInfoResp_msg
#define discovery_DeviceInfoQuery_fields &discovery_DeviceInfoQuery_msg
#define discovery_DeviceDomainInfoQuery_fields &discovery_DeviceDomainInfoQuery_msg
#define discovery_Message_fields &discovery_Message_msg

/* Maximum encoded size of messages (where known) */
/* discovery_DeviceInfoResp_size depends on runtime parameters */
/* discovery_Message_size depends on runtime parameters */
#define discovery_DeviceDomainInfoQuery_size     6
#define discovery_DeviceDomainInfoResp_size      17
#define discovery_DeviceInfoQuery_size           6
#define discovery_DeviceReadyResp_size           0
#define discovery_DeviceResetQuery_size          0
#define discovery_SetTransportSpeed_size         6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
