/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7-dev */

#include "protocol/device.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(discovery_DeviceResetQuery, discovery_DeviceResetQuery, AUTO)


PB_BIND(discovery_DeviceReadyResp, discovery_DeviceReadyResp, AUTO)


PB_BIND(discovery_SetTransportSpeed, discovery_SetTransportSpeed, AUTO)


PB_BIND(discovery_DeviceInfoResp, discovery_DeviceInfoResp, 2)


PB_BIND(discovery_DeviceDomainInfoResp, discovery_DeviceDomainInfoResp, AUTO)


PB_BIND(discovery_DeviceInfoQuery, discovery_DeviceInfoQuery, AUTO)


PB_BIND(discovery_DeviceDomainInfoQuery, discovery_DeviceDomainInfoQuery, AUTO)


PB_BIND(discovery_Message, discovery_Message, 2)






