/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7-dev */

#include "protocol/generic.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(generic_CmdResult, generic_CmdResult, AUTO)


PB_BIND(generic_Progress, generic_Progress, AUTO)


PB_BIND(generic_DebugMsg, generic_DebugMsg, AUTO)


PB_BIND(generic_VerboseMsg, generic_VerboseMsg, AUTO)


PB_BIND(generic_Message, generic_Message, AUTO)




