/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7-dev */

#include "protocol/esb/esb.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(esb_SetNodeAddressCmd, esb_SetNodeAddressCmd, AUTO)


PB_BIND(esb_SniffCmd, esb_SniffCmd, AUTO)


PB_BIND(esb_JamCmd, esb_JamCmd, AUTO)


PB_BIND(esb_SendCmd, esb_SendCmd, 2)


PB_BIND(esb_SendRawCmd, esb_SendRawCmd, 2)


PB_BIND(esb_PrimaryReceiverModeCmd, esb_PrimaryReceiverModeCmd, AUTO)


PB_BIND(esb_PrimaryTransmitterModeCmd, esb_PrimaryTransmitterModeCmd, AUTO)


PB_BIND(esb_StartCmd, esb_StartCmd, AUTO)


PB_BIND(esb_StopCmd, esb_StopCmd, AUTO)


PB_BIND(esb_Jammed, esb_Jammed, AUTO)


PB_BIND(esb_RawPduReceived, esb_RawPduReceived, 2)


PB_BIND(esb_PduReceived, esb_PduReceived, 2)


PB_BIND(esb_Message, esb_Message, 2)




